name: ML_intro
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.7.4=hf0a4a13_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py311hcc98501_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.2=py311hb9542d7_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - fonttools=4.53.1=py311hd3f4193_0
  - freetype=2.12.1=hadb7bae_2
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.26.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h267d04e_0
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=23_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=23_osxarm64_openblas
  - libcxx=18.1.8=h167917d_0
  - libdeflate=1.20=h93a5062_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=23_osxarm64_openblas
  - libopenblas=0.3.27=openmp_h517c56d_1
  - libpng=1.6.43=h091b4b1_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libtiff=4.6.0=h07db509_3
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.16=hf2054a2_0
  - libzlib=1.3.1=hfb2fe0b_1
  - llvm-openmp=18.1.8=hde57baf_0
  - matplotlib=3.9.1=py311ha1ab1f8_0
  - matplotlib-base=3.9.1=py311hba6b155_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=hb89a1cb_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=2.0.1=py311h4268184_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.3.1=hfb2fe0b_2
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py311h4b4568b_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py311hd7951ec_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - plotly=5.23.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py311hd3f4193_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - python=3.11.9=h932a869_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyzmq=26.0.3=py311h9bed540_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h92ec313_1
  - scikit-learn=1.5.1=py311hbfb48bc_0
  - scipy=1.14.0=py311hceeca8c_1
  - setuptools=71.0.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tenacity=8.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4.1=py311hd3f4193_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.5=hcc0f68c_4
  - zipp=3.19.2=pyhd8ed1ab_0
  - zstd=1.5.6=hb46c0d2_0
prefix: /Users/yusali/miniforge3/envs/ML_intro
